### ISSUE TITLE
Sessions Presenter

### ISSUE THREAD

**Issue by mtthsfrdrch** [GDGhamburg/devfest-app#4]
Thinking about doing the sessions overview a bit like this:
![device-2016-09-02-213100](https://cloud.githubusercontent.com/assets/1707189/18216057/b23d5a9e-7154-11e6-87b1-3610eb84b4ce.png)

Here each page would represent one stage for one day. So with 2 stages and 2 days, it would be 4 pages (+ maybe some more for workshops). So independent from how the data in firebase looks, the presenter of this screen basically could provide 2 types of lists:
- **StageDay-List** represents pages, one StageDay is one page, would be needed as soon as the screen starts so the ViewPager knows what items he has, a StageDay could have a date and maybe some infos about the stage 
- **Session-List** list of all sessions for one StageDay, as each StageDay needs one Session-List. it could be lazy loaded as soon as the page in the ViewPager gets instantiated or loaded upfront directly with each StageDay, not sure about this

This is just a rough idea how to structure the data this screen needs. Ideas are welcome ;)

**Comment by andretietz** [comment]
https://github.com/GDGhamburg/devfest-app/blob/mf/nav_drawer/app/src/main/java/de/devfest/data/SessionManager.java#L11

Session:
https://github.com/GDGhamburg/devfest-app/blob/mf/nav_drawer/app/src/main/java/de/devfest/model/Session.java

This should solve all problems you have already, no?
You can filter the outcoming items by track already

**Comment by mtthsfrdrch** [comment]
Hmm, but where do i get the tracks in the first place? Like it is now i don't even know how many tracks there are before querying all the sessions, right? In `TrackManager` there is just `getTrack(String trackId)`.
When i have to filter out the tracks from all the sessions, why do we have tracks in the database at all then? Then a track-name in all the session would be enough, wouldn't it? :wink:
Sure, i guess constructing the data how i need it, is possible with some iterating, filtering, collecting etc., but isn't that what the managers are there for? I'd prefer not to do heavy data-collecting operations in the presenters or maybe just to some small degrees (and totally not in the Views ;) ).

Aren't you looking for something to code? :stuck_out_tongue_winking_eye:

I think `TrackManager` needs something like `List<Track> getTracks()` and `SessionManager` needs something like `getSessionsForTrackAndDay(...)`. Then the question is where do we get the days/timeframes from? Maybe we should really have something like start- and end-date of the conference in firebase.  
As soon as the View has the tracks and days it could tell the presenter which track for which day it scrolls in and the presenter delivers the session-list for that track on that day.

Or do i just don't get something here? :tired_face:
